export const ListaRedesSociales = {
  es: [
    {
      ArialLabel: "Visitar la página oficial de USMX en Facebook",
      Titulo: "Facebook de USMX - Conectando Fronteras",
      URL: "#",
      SVG: "FACEBOOK",
      Alt: "Icono de Facebook de USMX - Conectando Fronteras",
      Tamaño: "30",
    },
    {
      ArialLabel: "Visitar el perfil oficial de USMX en Instagram",
      Titulo: "Instagram de USMX - Conectando Fronteras",
      URL: "#",
      SVG: "INSTAGRAM",
      Alt: "Icono de Instagram de USMX - Conectando Fronteras",
      Tamaño: "30",
    },
    {
      ArialLabel: "Visitar el perfil oficial de USMX en X",
      Titulo: "X de USMX - Conectando Fronteras",
      URL: "#",
      SVG: "X",
      Alt: "Icono de X de USMX - Conectando Fronteras",
      Tamaño: "30",
    },
    {
      ArialLabel: "Visitar el perfil oficial de USMX en TikTok",
      Titulo: "TikTok de USMX - Conectando Fronteras",
      URL: "#",
      SVG: "TIKTOK",
      Alt: "Icono de TikTok de USMX - Conectando Fronteras",
      Tamaño: "30",
    },
  ],
  en: [
    {
      ArialLabel: "Visit USMX's official Facebook page",
      Titulo: "USMX on Facebook - Connecting Frontiers",
      URL: "#",
      SVG: "FACEBOOK",
      Alt: "USMX Facebook icon - Connecting Frontiers",
      Tamaño: "30",
    },
    {
      ArialLabel: "Visit USMX's official Instagram profile",
      Titulo: "USMX on Instagram - Connecting Frontiers",
      URL: "#",
      SVG: "INSTAGRAM",
      Alt: "USMX Instagram icon - Connecting Frontiers",
      Tamaño: "30",
    },
    {
      ArialLabel: "Visit USMX's official X profile",
      Titulo: "USMX on X - Connecting Frontiers",
      URL: "#",
      SVG: "X",
      Alt: "USMX X icon - Connecting Frontiers",
      Tamaño: "30",
    },
    {
      ArialLabel: "Visit USMX's official TikTok profile",
      Titulo: "USMX on TikTok - Connecting Frontiers",
      URL: "#",
      SVG: "TIKTOK",
      Alt: "USMX TikTok icon - Connecting Frontiers",
      Tamaño: "30",
    },
  ],
};
