export const navbarOpciones = {
  es: [
    {
      URL: "/es/RastrearPaquete",
      SVG: "RASTREO",
      Alt: "Icono de rastreo de paquetes en la aplicación USMX",
      Tamaño: "30",
      NombreSeccion: "Rastreo",
      Titulo: "Rastrear tu paquete en tiempo real con USMX",
    },
    {
      URL: "/es/Servicios",
      SVG: "SERVICIOS",
      Alt: "Icono de servicios proporcionados por USMX",
      Tamaño: "30",
      NombreSeccion: "Servicios",
      Titulo: "Explora los servicios profesionales ofrecidos por USMX",
    },
    {
      URL: "/es/Nosotros",
      SVG: "INFORMACION",
      Alt: "Icono de información sobre USMX",
      Tamaño: "26",
      NombreSeccion: "Nosotros",
      Titulo: "Conoce más sobre USMX y nuestra misión",
    },
    {
      URL: "/es/Contacto",
      SVG: "CORREO",
      Alt: "Icono de contacto con USMX",
      Tamaño: "30",
      NombreSeccion: "Contacto",
      Titulo: "Contacta a USMX para consultas y soporte",
    },
    {
      URL: "https://www.usmxxpress.net/",
      SVG: "SISTEMA",
      Alt: "Icono de acceso al sistema de USMX",
      Tamaño: "24",
      NombreSeccion: "Sistema",
      Titulo: "Accede al sistema de USMX para gestionar tus paquetes",
    },
  ],
  en: [
    {
      URL: "/en/TrackPackage",
      SVG: "RASTREO",
      Alt: "Package tracking icon in the USMX app",
      Tamaño: "30",
      NombreSeccion: "Tracking",
      Titulo: "Track your package in real time with USMX",
    },
    {
      URL: "/en/Services",
      SVG: "SERVICIOS",
      Alt: "Icon for services provided by USMX",
      Tamaño: "30",
      NombreSeccion: "Services",
      Titulo: "Explore the professional services offered by USMX",
    },
    {
      URL: "/en/AboutUs",
      SVG: "INFORMACION",
      Alt: "Icon for information about USMX",
      Tamaño: "26",
      NombreSeccion: "About Us",
      Titulo: "Learn more about USMX and our mission",
    },
    {
      URL: "/en/Contact",
      SVG: "CORREO",
      Alt: "Icon for contacting USMX",
      Tamaño: "30",
      NombreSeccion: "Contact",
      Titulo: "Contact USMX for inquiries and support",
    },
    {
      URL: "https://www.usmxxpress.net/",
      SVG: "SISTEMA",
      Alt: "Icon for accessing the USMX system",
      Tamaño: "24",
      NombreSeccion: "System",
      Titulo: "Access the USMX system to manage your packages",
    },
  ],
};
