export const OpcionesDeContacto = {
  es: [
    {
      tipo: "text",
      textoLabel: "Nombre",
      id: "Nombre",
      name: "Nombre",
      placeholder: "Ingresa tu nombre",
      maxlength: "50",
      tamaño: "",
    },
    {
      tipo: "text",
      textoLabel: "Apellidos",
      id: "Apellidos",
      name: "Apellidos",
      placeholder: "Ingresa tus apellidos",
      maxlength: "50",
      tamaño: "",
    },
    {
      tipo: "email",
      textoLabel: "Correo",
      id: "Correo",
      name: "Correo",
      placeholder: "Ingresa tu correo",
      maxlength: "100",
      tamaño: "",
    },
    {
      tipo: "tel",
      textoLabel: "Teléfono",
      id: "Telefono",
      name: "Telefono",
      placeholder: "Ingresa tu télefono",
      pattern: "[0-9]{10}",
      maxlength: "10",
      tamaño: "",
    },
    {
      tipo: "textarea",
      textoLabel: "Mensaje",
      id: "Mensaje",
      name: "Mensaje",
      placeholder: "Escribe tu mensaje aqui...",
      maxlength: "1000",
      textArea: true,
      tamaño: "Completo",
    },
  ],
  en: [
    {
      tipo: "text",
      textoLabel: "Name",
      id: "Name",
      name: "Name",
      placeholder: "Enter your name",
      maxlength: "50",
      tamaño: "",
    },
    {
      tipo: "text",
      textoLabel: "Last Name",
      id: "Last Name",
      name: "Last Name",
      placeholder: "Enter your last name",
      maxlength: "50",
      tamaño: "",
    },
    {
      tipo: "email",
      textoLabel: "Email",
      id: "Email",
      name: "Email",
      placeholder: "Enter your email",
      maxlength: "100",
      tamaño: "",
    },
    {
      tipo: "tel",
      textoLabel: "Phone",
      id: "Phone",
      name: "Phone",
      placeholder: "Enter your phone",
      pattern: "[0-9]{10}",
      maxlength: "10",
      tamaño: "",
    },
    {
      tipo: "textarea",
      textoLabel: "Message",
      id: "Message",
      name: "Message",
      placeholder: "Write your message here...",
      maxlength: "1000",
      textArea: true,
      tamaño: "Completo",
    },
  ],
};
